
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: drift_map_api_development

test:
  <<: *default
  database: drift_map_api_test

production:
  <<: *default
  database: drift_map_api_production
  username: ethan
  password: <%= ENV['DRIFT_MAP_API_DATABASE_PASSWORD'] %>
